create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  external_id text not null unique,
  first_name text,
  last_name text,
  full_name text not null,
  phone text,
  email text,
  city text,
  address text,
  status text not null default 'new',
  order_type text,
  order_method text,
  utm_source text,
  total_amount integer not null default 0,
  crm_created_at timestamptz,
  crm_updated_at timestamptz,
  raw_payload jsonb not null,
  synced_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_external_id text not null references public.orders(external_id) on delete cascade,
  line_index integer not null,
  product_name text not null,
  quantity integer not null,
  unit_price integer not null,
  line_total integer not null
);

create unique index if not exists order_items_order_external_id_line_index_idx
  on public.order_items(order_external_id, line_index);

create table if not exists public.telegram_notifications (
  id bigint generated by default as identity primary key,
  order_external_id text not null references public.orders(external_id) on delete cascade,
  rule_key text not null,
  sent_at timestamptz not null default now(),
  unique(order_external_id, rule_key)
);

create table if not exists public.order_sync_events (
  id bigint generated by default as identity primary key,
  order_external_id text not null references public.orders(external_id) on delete cascade,
  event_type text not null,
  event_source text not null,
  payload_before jsonb,
  payload_after jsonb,
  changed_fields jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists order_sync_events_order_external_id_created_at_idx
  on public.order_sync_events(order_external_id, created_at desc);

create table if not exists public.app_settings (
  key text primary key,
  value jsonb not null,
  updated_at timestamptz not null default now()
);

create table if not exists public.telegram_recipients (
  id bigint generated by default as identity primary key,
  chat_id text not null unique,
  label text not null,
  is_enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.telegram_rules (
  id bigint generated by default as identity primary key,
  key text not null unique,
  label text not null,
  is_enabled boolean not null default true,
  threshold_amount integer not null default 50000,
  recipient_mode text not null default 'all_enabled',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
