create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  external_id text not null unique,
  first_name text,
  last_name text,
  full_name text not null,
  phone text,
  email text,
  city text,
  address text,
  status text not null default 'new',
  order_type text,
  order_method text,
  utm_source text,
  total_amount integer not null default 0,
  crm_created_at timestamptz,
  crm_updated_at timestamptz,
  raw_payload jsonb not null,
  synced_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_external_id text not null references public.orders(external_id) on delete cascade,
  line_index integer not null,
  product_name text not null,
  quantity integer not null,
  unit_price integer not null,
  line_total integer not null
);

create unique index if not exists order_items_order_external_id_line_index_idx
  on public.order_items(order_external_id, line_index);

create table if not exists public.telegram_notifications (
  id bigint generated by default as identity primary key,
  order_external_id text not null references public.orders(external_id) on delete cascade,
  rule_key text not null,
  sent_at timestamptz not null default now(),
  unique(order_external_id, rule_key)
);
